name: story_view
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.16.6
homepage: https://github.com/blackmann/story_view

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  rxdart: ^0.27.7
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
